### ISSUE TITLE
Траектория почему-то не отображается на экране

### ISSUE THREAD

**Issue by AnastasiyaKropacheva** [AnastasiyaKropacheva/WPF2022-github#2]

**Comment by justjune** [comment]
Оператор 88 --- ошибочен! Его надо убрать:   //Data.tr.Points = new PointCollection();
Операторы:
                //Data.win.UpdateLayout();
                //Data.win.InvalidateVisual();
Тоже нужно убрать. (Они вредить не будут, но не нужны.)
